### ISSUE TITLE
方案是否支持添加到Win10的双拼输入法内

### ISSUE THREAD

**Issue by WilliamZY** [sp-study-group/ossp-guan#14]
![image](https://user-images.githubusercontent.com/12370751/43194851-c1314642-9046-11e8-871f-deac712cb1f7.png)

这是我尝试的结果, 不明白"请确保所有的音节都对应到有效的按键上" 到底指的是什么

**Comment by 71e6fd52** [comment]
提醒你设置好，防止你有音节打不出来

**Comment by yahvk-cuna** [comment]
把 `ue` 绑到 `T` 上就可以

**Comment by WilliamZY** [comment]
谢谢 现在终于可以添加了

**Comment by yahvk-cuna** [comment]
不 close ？
