### ISSUE TITLE
怎么和官网的布局不一样啊？

### ISSUE THREAD

**Issue by cjahv** [sp-study-group/ossp-guan#7]
![image](https://user-images.githubusercontent.com/15372793/30904191-d830297a-a3a3-11e7-945e-0f811b14912d.png)

**Comment by R0uter** [comment]
你看的是小鹤双拼的官网，小鹳的官网就是这里。https://github.com/sp-study-group/ossp-guan

> 小鹳 是专门为使用全拼打字的新双拼用户设计的一款双拼方案，它集成了普通全拼的一些特性，比如两字母韵母直接输入作为韵母，同时，也借鉴和使用了双拼演进过程中的最新的理念比如“飞键”技术来兼容大部份双拼习惯并解决常见的争议问题。

**Comment by cjahv** [comment]
好吧。。。眼拙。

**Comment by R0uter** [comment]
XD 

ok，那就关掉了。
